services:
  - type: web
    name: color-by-number
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt && pip install jinja2==3.1.2
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: GRADIO_ANALYTICS_ENABLED
        value: "False"
    healthCheckPath: /
    autoDeploy: true
